name: Run integration scripts

on: push

jobs:
  test:
    name: Run integration scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Show PHPCS sniffs
        run: ./vendor/bin/phpcs -i

      - name: Show version info
        run: |
          php --version
          ./vendor/bin/psalm --version
          ./vendor/bin/phpcs --version
          ./vendor/bin/phplint --version

      - name: Run PHP_CodeSniffer
        run: composer cs

      - name: Run PHPLint
        run: composer lint

      - name: Run Psalm
        run: composer psalm
